# Python Tutorial

## Basit matematiksel işlemler

In [1]:
# Bu bir türkçe karakterli yorum satırıdır. Eðer sayfanın başına "encoding utf-8" satırını

In [3]:
import math # math kütüphanesini import eder

In [4]:
print ("Hello world") # Ekrana metin yazar. Tırnak işareti kullanmazsan hata verir

Hello world


In [5]:
print (1) # Ekranan sayı yazar

1


In [6]:
# Ekrana toplama işlemnin sonucunu yazar
print (1+2)

3


In [7]:
print ("ali"+2)

TypeError: can only concatenate str (not "int") to str

In [8]:
print (int("ali")+2)

ValueError: invalid literal for int() with base 10: 'ali'

In [9]:
print (True+2)

3


In [10]:
print (True+False)

1


In [11]:
# Ekrana çıkarma işlemnin sonucunu basar
print (4-7)

-3


In [12]:
# Ekrana çarpım işlemnin sonucunu yazar
print (2*3)

6


In [13]:
print ("ali" * 3)

alialiali


In [14]:
print (False * 3)

0


In [15]:
# ekranan sayının üssü alır sonucu yazar
print (2**3)

8


In [16]:
print (2***3)

SyntaxError: invalid syntax (<ipython-input-16-216c17210ef7>, line 1)

In [17]:
print ("ali"**3)

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

In [18]:
# Ekranan bölme işlemi sonucu yazar
print (5/2)

2.5


In [19]:
print (5/False)

ZeroDivisionError: division by zero

In [20]:
# Ekrana bölme işleminin kalanını basar
print (10%3)

1


In [21]:
print (max(3,8,1,10,5))

10


In [22]:
print (max(3,True,1,10,5))

10


In [23]:
print (min(3,8,1,10,5))

1


In [24]:
print (min(3,8,1,10,5, False))

False


### Math kütüphane fonksiyonları ile matematiksel işlemler

In [25]:
# 'sin' is not defined hatası veriri çünkü math kütüphanesinin bir fonksiyonudur
print (sin(30))

NameError: name 'sin' is not defined

In [26]:
print (math.sin(30))

-0.9880316240928618


In [27]:
# Sayının karekökünü ekrana basar
print (math.sqrt(4) )

2.0


## Değişken tanımı

In [28]:
# Hata veriri "NameError: name 'x' is not defined" x tanımıyorum
print (x)

NameError: name 'x' is not defined

In [29]:
x = 1

In [30]:
print (x)

1


In [31]:
x = "hello world"

In [32]:
print (x)

hello world


In [33]:
print ("x")

x


In [35]:
x = 3
y = 5

In [36]:
x = x+y

In [37]:
print (x)

8


In [38]:
x=x**x

In [39]:
print (x)

16777216


In [40]:
y += y # = y = y+y

In [41]:
print (y)

10


### swap işlemi

In [42]:
x = 2
y = 3

In [43]:
tmp = x # X'i geçici dosyada tut

In [44]:
x = y

In [45]:
y = tmp # geçici dosyada tuttuğun x değerini y'ye ata

In [46]:
print (x,y,tmp)

3 2 2


### String birleştirme

In [51]:
string1 = "deneme1"
string2 = "deneme2"
string3 = string1+string2

In [52]:
print (string1, string2, string3)

deneme1 deneme2 deneme1deneme2


In [53]:
print ("Substring işlemleri :", string3[0], string3[5], string3[2:5], string3[5:], string3[:5])


Substring işlemleri : d e nem e1deneme2 denem


In [54]:
print ("string boyu : ", len(string3))

string boyu :  14


## if condition ve mantıksal opeartörler

< > <= >= == != her biri için if örneği yapalım, özellikle == ve = farkı

Önemli assigment işlemi ve eşitlik kontrolü
&& || !

In [47]:
# Boşluk intend kavramı ve hatalar
if 3>2:
    print ("if doğru olduğunda")
else:
    print ("else yanlış olduğu durum")

if doğru olduğunda


In [48]:
x = 3
y = 9

In [49]:
if x > y:
    print ("x y'den büyük")
else:
    print ("y x'den büyük")

y x'den büyük


## Collections

Python has several built-in types that are useful for storing and manipulating data: list, tuple, dict. Here is the official Python documentation on these types (and many others): https://docs.python.org/3/library/stdtypes.html.

### Lists

Lists are mutable arrays. Let's see how they work.

In [ ]:
names = ["Zach", "Jay"]

In [ ]:
# Index into list by index
print(names[0])

Zach


In [ ]:
# Append to list (appends to end of list)
names.append("Richard")
print(names)

['Zach', 'Jay', 'Richard']


In [ ]:
# Get length of list
print(len(names))

3


In [ ]:
# Concatenate two lists
# += operator is a short hand for list1 = list1 + list2 (can also be used for -, *, / and on other types of variables)
names += ["Abi", "Kevin"]
print(names)

['Zach', 'Jay', 'Richard', 'Abi', 'Kevin']


In [ ]:
# Two ways to create an empty list
more_names = []
more_names = list()

In [ ]:
# Create a list that contains different data types, this is allowed in Python
stuff = [1, ["hi", "bye"], -0.12, None]
print(stuff)

[1, ['hi', 'bye'], -0.12, None]


List slicing is a useful way to access a slice of elements in a list.

In [ ]:
numbers = [0, 1, 2, 3, 4, 5, 6]

# Slices from start index (inclusive) to end index (exclusive)
print(numbers[0:3])

[0, 1, 2]


In [ ]:
# When start index is not specified, it is start of list
# When end index is not specified, it is end of list
print(numbers[:3])
print(numbers[5:])

[0, 1, 2]
[5, 6]


In [ ]:
# : takes the slice of all elements along a dimension, is very useful when working with numpy arrays
print(numbers[:])

[0, 1, 2, 3, 4, 5, 6]


In [ ]:
# Negative index wraps around, start counting from the end of list
print(numbers[-1])
print(numbers[-3:])
print(numbers[3:-2])

6
[4, 5, 6]
[3, 4]


### Tuples

Tuples are immutable arrays. Let's see how they work.

In [ ]:
# Use parentheses for tuples, square brackets for lists
names = ("Zach", "Jay")

In [ ]:
# Syntax for accessing an element and getting length are the same as lists
print(names[0])
print(len(names))

Zach
2


In [ ]:
# But unlike lists, tuples do not support item re-assignment
names[0] = "Richard"

TypeError: ignored

In [ ]:
# Create an empty tuple
empty = tuple()
print(empty)

# Create a tuple with a single item, the comma is important
single = (10,)
print(single)

()
(10,)


## Dictionary

Dictionaries are hash maps. Let's see how they work.

In [ ]:
# Two ways to create an empty dictionary
phonebook = {}
phonebook = dict()

In [ ]:
# Create dictionary with one item
phonebook = {"Zach": "12-37"}
# Add another item
phonebook["Jay"] = "34-23"

In [ ]:
# Check if a key is in the dictionary
print("Zach" in phonebook)
print("Kevin" in phonebook)

True
False


In [ ]:
# Get corresponding value for a key
print(phonebook["Jay"])

34-23


In [ ]:
# Delete an item
del phonebook["Zach"]
print(phonebook)

{'Jay': '34-23'}


## Loops

In [ ]:
# Basic for loop
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
# To iterate over a list
names = ["Zach", "Jay", "Richard"]
for name in names:
    print(name)

Zach
Jay
Richard


In [ ]:
# To iterate over indices and values in a list
# Way 1
for i in range(len(names)):
    print(i, names[i])

print("---")

# Way 2
for i, name in enumerate(names):
    print(i, name)

0 Zach
1 Jay
2 Richard
---
0 Zach
1 Jay
2 Richard


In [ ]:
# To iterate over a dictionary
phonebook = {"Zach": "12-37", "Jay": "34-23"}

# Iterate over keys
for name in phonebook:
    print(name)

print("---")

# Iterate over values
for number in phonebook.values():
    print(number)

print("---")

# Iterate over keys and values
for name, number in phonebook.items():
    print(name, number)

Zach
Jay
---
12-37
34-23
---
Zach 12-37
Jay 34-23


## NumPy
NumPy is a Python library, which adds support for large, multi-dimensional arrays and matrices, along with a large collection of optimized, high-level mathematical functions to operate on these arrays.

You may need to install numpy first before importing it in the next cell.

There are many ways to manage your packages, but the workflow we suggest for this class is to use Anaconda.
 - Download Anaconda. Create a conda environment when you work on a new project.
 - Activate your conda environment and install libraries using conda or pip if they are not available in conda.
 - If you are running scripts on command line, run inside your conda environment.
 - If you are using a Jupyter notebook, add your conda environment to your Jupyter notebook: https://towardsdatascience.com/get-your-conda-environment-to-show-in-jupyter-notebooks-the-easy-way-17010b76e874. Create your Jupyter notebook and verify you're in your conda environment kernel (top right of notebook should display the name). If you're not, go to the Kernel tab on the top left and click Change kernel to change to your conda environment kernel.

In [ ]:
# Import numpy
import numpy as np

In [ ]:
# Create numpy arrays from lists
x = np.array([1,2,3])
a = np.array([[1,2,3]])


y = np.array([[3,4,5]])
z = np.array([[6,7],[8,9]])

# Let's take a look at their shapes.
# When working with numpy arrays, .shape will be a very useful debugging tool
print(x.shape)
print(y.shape)
print()
print(z)
print(z.shape)

(3,)
(1, 3)

[[6 7]
 [8 9]]
(2, 2)


Vectors can be represented as 1-D arrays of shape (N,) or 2-D arrays of shape (N, 1) or (1, N). But it's important to note that the shapes (N,), (N, 1), and (1,N) are not the same and may result in different behavior (we'll see some examples below involving matrix multiplication and broadcasting).

Matrices are generally represented as 2-D arrays of shape (M, N).

The best way to ensure your code gives you the behavior you expect is to keep track of your array shapes and try out small test cases or refer back to documentation when you are unsure.

In [ ]:
a = np.arange(10)
b = a.reshape((5, 2))
print(a)
print()
print(b)

[0 1 2 3 4 5 6 7 8 9]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Array Operations

There are many NumPy operations that can be used to reduce a numpy array along an axis.

Let's look at the np.max operation (documentation: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html).

In [ ]:
x = np.array([[1,2],[3,4], [5, 6]])
print(x)
print()
print(x.shape)

[[1 2]
 [3 4]
 [5 6]]

(3, 2)


In [ ]:
print(np.max(x, axis = 1))

[2 4 6]


In [ ]:
print(np.max(x, axis = 1).shape)

(3,)


In [ ]:
print(np.max(x, axis = 1, keepdims = True))

[[2]
 [4]
 [6]]


In [ ]:
print(np.max(x, axis = 1, keepdims = True).shape)

(3, 1)


Next, let's look at some matrix operations. Let's take an element-wise product (Hadamard product).

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 3], [3, 3]])
print(A)
print(B)
print("---")
print(A * B)

[[1 2]
 [3 4]]
[[3 3]
 [3 3]]
---
[[ 3  6]
 [ 9 12]]


We can do matrix multiplication with np.matmul or @.

In [ ]:
# One way to do matrix multiplication
print(np.matmul(A, B))

# Another way to do matrix multiplication
print(A @ B)

[[ 9  9]
 [21 21]]
[[ 9  9]
 [21 21]]


We can take the dot product or a matrix vector product with np.dot.

In [ ]:
u = np.array([1, 2, 3])
v = np.array([1, 10, 100])

print(np.dot(u, v))

# Can also call numpy operations on the numpy array, useful for chaining together multiple operations
print(u.dot(v))

321
321


In [ ]:
W = np.array([[1, 2], [3, 4], [5, 6]])
print(v.shape)
print(W.shape)

# This works.
print(np.dot(v, W))
print(np.dot(v, W).shape)

(3,)
(3, 2)
[531 642]
(2,)


In [ ]:
# This does not. Why?
print(np.dot(W, v))

ValueError: ignored

In [ ]:
# We can fix the above issue by transposing W.
print(np.dot(W.T, v))
print(np.dot(W.T, v).shape)

[531 642]
(2,)


###  Indexing

Slicing / indexing numpy arrays is a extension of the Python concept of slicing (lists) to N dimensions.

In [ ]:
x = np.random.random((3, 4))

# Selects all of x
print(x[:])

[[0.59539247 0.44943372 0.6974783  0.74086032]
 [0.05439564 0.49684488 0.53743562 0.45502382]
 [0.84378783 0.14212709 0.65069361 0.81998942]]


In [ ]:
# Selects the 0th and 2nd rows
print(x[np.array([0, 2]), :])

print("---")

# Selects 1st row as 1-D vector and and 1st through 2nd elements
print(x[1, 1:3])

[[0.08741133 0.23348194 0.10838167 0.22120641]
 [0.77255779 0.00482836 0.10692647 0.11250782]]
---
[0.02177989 0.17319822]


In [ ]:
# Boolean indexing
print(x[x > 0.5])

[0.59539247 0.6974783  0.74086032 0.53743562 0.84378783 0.65069361
 0.81998942]


In [ ]:
# 3-D vector of shape (3, 4, 1)
print(x[:, :, np.newaxis])

[[[0.08741133]
  [0.23348194]
  [0.10838167]
  [0.22120641]]

 [[0.36210074]
  [0.02177989]
  [0.17319822]
  [0.19521131]]

 [[0.77255779]
  [0.00482836]
  [0.10692647]
  [0.11250782]]]


### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

**General Broadcasting Rules**

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when:
- they are equal, or
- one of them is 1 (in which case, elements on the axis are repeated along the dimension)

More details: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [ ]:
x = np.random.random((3, 4))

y = np.random.random((3, 1))
z = np.random.random((1, 4))

# In this example, y and z are broadcasted to match the shape of x.
# y is broadcasted along dim 1.
s = x + y
# z is broadcasted along dim 0.
p = x * z

In [ ]:
print(x.shape)
print()
print(y.shape)
print(s.shape)

(3, 4)

(3, 1)
(3, 4)


In [ ]:
print(x.shape)
print()
print(s.shape)
print(p.shape)

(3, 4)

(3, 4)
(3, 4)


In [ ]:
a = np.zeros((3, 3))
b = np.array([[1, 2, 3]])
print(a)
print()
print(a+b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


Let's look at a more complex example.

In [ ]:
a = np.random.random((3, 4))
b = np.random.random((3, 1))
c = np.random.random((3, ))

What is the expected broadcasting behavior for these operations? What do the following operations give us? What are the resulting shapes?

In [ ]:
result1 = b + b.T

print(b.shape)
print(b.T.shape)
print(result1.shape)
print(result1)

(3, 1)
(1, 3)
(3, 3)
[[0.11647105 0.94317868 0.80520919]
 [0.94317868 1.76988632 1.63191683]
 [0.80520919 1.63191683 1.49394734]]


In [ ]:
result2 = a + c

print(a.shape)
print(c.shape)
print(result2.shape)
print(result2)

ValueError: ignored

In [ ]:
result3 = b + c

print(b.shape)
print(c.shape)
print(result3.shape)
print(result3)

(3, 1)
(3,)
(3, 3)
[[0.70180112 0.31264318 0.20256093]
 [1.52850876 1.13935081 1.02926857]
 [1.39053927 1.00138132 0.89129908]]


### Efficient NumPy Code

When working with numpy arrays, avoid explicit for-loops over indices/axes at all costs. For-loops will dramatically slow down your code (~10-100x).

We can time code using the %%timeit magic. Let's compare using explicit for-loop vs. using numpy operations.

In [ ]:
%%timeit
x = np.random.rand(1000, 1000)
for i in range(100, 1000):
    for j in range(x.shape[1]):
        x[i, j] += 5

459 ms ± 10.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
x = np.random.rand(1000, 1000)
x[np.arange(100,1000), :] += 5

12.2 ms ± 143 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Dosya okuma yazma işlemleri

In [55]:
# Dosyayı aç
file = open("deneme.txt","a+")

In [56]:
string1 = "metin 1 "
string2 = "metin 2 "
string3 = "metin 3 ve diğerleri "+string1+string2

In [57]:
# Dosyaya yaz
file.write(string1)
file.write(string2)
file.write(string3)
file.close() # Dosyayı kapat

In [59]:
# Dosyayı aç
file = open("deneme.txt","r")
print (file) # Size dosyanın içeriğini vermez, dosyanın durumunu verir : "<open file 'deneme.txt', mode 'r' at 0x00000000021B4150>" sonucu verir.


<_io.TextIOWrapper name='deneme.txt' mode='r' encoding='UTF-8'>


### Dosyanın içeriğini iki şekilde okuyabilirsiniz

In [60]:
# 1. Durum
f = file.read() # Dosyayı read fonksiyonuyla oku ve bir değişkenen ata daha sonra o değişkeni print et
print (f+"\n")

metin 1 metin 2 metin 3 ve diğerleri metin 1 metin 2 



In [61]:
# 2. Durum dosyayı for döngüsüyle oku ve her satırı ekrana bas
for satir in file: # Satır satır dosyayı oku
    print (satir)

In [62]:
# Dosyanın içindeki metinleri harf harf okumak için bu ikisini birleştirelim

for satir in f:
    print (satir)

m
e
t
i
n
 
1
 
m
e
t
i
n
 
2
 
m
e
t
i
n
 
3
 
v
e
 
d
i
ğ
e
r
l
e
r
i
 
m
e
t
i
n
 
1
 
m
e
t
i
n
 
2
 


## Fonksiyon tanımlama

In [64]:
def fonkA():
    print ("Ben A fonksiyonum")

In [65]:
fonkA() # fonksiyonu çağıralım

Ben A fonksiyonum


In [66]:
def fonkB():
    print ("Ben B fonksiyonum. Şimdi A fonksiyonunu çağıracağım")

In [67]:
fonkB()

Ben B fonksiyonum. Şimdi A fonksiyonunu çağıracağım


In [68]:
# parametre alan fonksiyon aldığı paramtreyi ekrana yazıyor
def fonk2(param):
	print (param)

In [69]:
# fonksiyonu çağıralim
fonk2("deneme parametresi bakalım ne olacak ")

deneme parametresi bakalım ne olacak 


In [70]:
#birden fazla paramtre alan fonksiyon
def fonk3(param, param2):
	print (param)
	print (param2)
	print (param+param2)

In [71]:
#fonksiyonu çağıralım
fonk3("parametre 1 ","parametre 2 ")

parametre 1 
parametre 2 
parametre 1 parametre 2 


In [75]:
def dort_islem(param1, param2, islemkod):

        if islemkod=="topla":
            return param1+param2
        elif islemkod == "çarp":
            return param1*param2
        elif islemkod == "böl":
            return param1/param2
        elif islemkod == "kalan":
            return param1%param2
        elif islemkod == "çıkar":
            return param1-param2
        else:
            print ("İşlem Kod Tanınamadı : "+islemkod)

In [76]:
dort_islem(3, 5, "kalan")

3

In [77]:
def asalmi(asal_sayi):
    for sayi in range(2,asal_sayi):
        if(asal_sayi%sayi) == 0:
            return False
    return True

In [79]:
asalmi(4)

False

In [80]:
asalmi(4093859020859238509823098592380598230985092385902830958092380958920350928309438675230)

False

In [85]:
asalmi(409385902085923850982309859238059823098509238590283095809238095892035092830943867527823485623476587365892369586238743876583273598671982359812739586165273658236988561913759173968713985798314768934176981730957176013490671903476091734069170936709134767493760917039678107697143097609739874698175901881037469173968714308019327809755742487390670934769817235719273960176897423897019809178478927091784309617409760941743607109717)

False

In [87]:
def asal_sayilar(limit):
    for sayi in range(1,limit):
        if asalmi(sayi):
            print (sayi)

In [91]:
asal_sayilar(200000000)

1
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997
1009
1013
1019
1021
1031
1033
1039
1049
1051
1061
1063
1069
1087
1091
1093
1097
1103
1109
1117
1123
1129
1151
1153
1163
1171
1181
1187
1193
1201
1213
1217
1223
1229
1231
1237
1249
1259
1277
1279
1283
1289
1291
1297
1301
1303
1307
1319
1321
1327
1361
1367
1373
1381
1399
1409
1423
1427
1429
1433
1439
1447
1451
1453
1459
1471
1481
1483
1487
1489
1493
1499


KeyboardInterrupt: 

In [92]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

In [93]:
var1 = factorial(4)
var2 = factorial(100)

In [94]:
print (var1, var2)

24 93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


In [95]:
def fibonacci(n):
    if n == 0:
        return 1
    elif n == 1:
        return 1
    else:
        return fibonacci(n-2)+fibonacci(n-1)

In [96]:
fibonacci(5)

8

In [97]:
def pritnAllFibonacciNum(n):
    print ("Fibonacci Sayılarını Sıralıyorum : ")
    print ("Sıra : "+"   Değer : ")
    for sayi in range (0,n):
        print (sayi,fibonacci(sayi))

In [98]:
pritnAllFibonacciNum(6)

Fibonacci Sayılarını Sıralıyorum : 
Sıra :    Değer : 
0 1
1 1
2 2
3 3
4 5
5 8


## Link crawler

In [100]:
! pip install requests
! pip install beautifulsoup4


In [103]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse

def extract_links(url):
    """
    Verilen URL'den bağlantıları çıkartan fonksiyon.

    Args:
    - url (str): Bağlantıları çıkartılacak URL.

    Returns:
    - set: Çıkartılan bağlantıları içeren küme.
    """
    # URL'yi kontrol etme
    if not urlparse(url).scheme or not urlparse(url).netloc:
        url = "http://" + url

    # HTTP GET isteği gönderme
    try:
        response = requests.get(url)
    except requests.exceptions.RequestException as e:
        print(f"Hata: {e}")
        return set()

    # Sayfa içeriğini BeautifulSoup kullanarak çözümleme
    soup = BeautifulSoup(response.text, 'html.parser')

    # Tüm bağlantıları toplama
    links = set()
    for anchor in soup.find_all('a', href=True):
        link = urljoin(url, anchor['href'])
        links.add(link)

    return links

def crawl_website(start_url, output_file="output_links.txt"):
    """
    Verilen başlangıç URL'sinden başlayarak web sitesini taramak için fonksiyon.

    Args:
    - start_url (str): Taramaya başlanacak başlangıç URL'si.
    - output_file (str): Bağlantıların kaydedileceği dosya adı.
    """
    visited_links = set()
    queue = [start_url]

    while queue:
        current_url = queue.pop(0)

        # Eğer ziyaret edilmişse atla
        if current_url in visited_links:
            continue

        print(f"Taranan URL: {current_url}")

        # URL'den bağlantıları çıkartma
        links = extract_links(current_url)

        # Ziyaret edilen bağlantıları listeye ekleme
        visited_links.add(current_url)

        # Yeni bağlantıları kuyruğa ekleme
        queue.extend(links - visited_links)

        # Bağlantıları dosyaya yazma
        with open(output_file, 'a') as file:
            file.write(f"Taranan URL: {current_url}\n")
            for link in links:
                file.write(f"{link}\n")

    print("Tarama tamamlandı. Bağlantılar dosyaya yazıldı:", output_file)

In [102]:
start_url = "http://www.nytimes.com"  # Başlangıç URL'sini değiştirebilirsiniz
output_file = "output_links.txt"   # Çıkartılan bağlantıların kaydedileceği dosya
crawl_website(start_url, output_file)

Taranan URL: http://www.nytimes.com
Taranan URL: https://cooking.nytimes.com/topics/healthy-recipes
Taranan URL: https://www.nytimes.com/wirecutter/gifts/
Taranan URL: https://www.nytimes.com/2024/01/17/opinion/north-korea-war.html
Taranan URL: https://www.nytimes.com/newsletters/watching
Taranan URL: https://cooking.nytimes.com/topics/vegan-recipes
Taranan URL: http://www.nytimes.com/ca/
Taranan URL: https://www.nytimes.com/section/politics
Taranan URL: http://www.nytimes.com/privacy/manage-settings
Taranan URL: https://www.nytimes.com/2024/01/18/podcasts/gaza-ukraine-trump-haley.html
Taranan URL: https://theathletic.com/football/mls/
Taranan URL: https://www.nytimes.com/column/modern-love-podcast
Taranan URL: https://theathletic.com/nhl/
Taranan URL: https://www.nytimes.com/spotlight/opinion-video
Taranan URL: https://www.nytimes.com/2024/01/18/arts/television/jimmy-fallon-vivek-ramaswamy-trump.html
Taranan URL: http://www.nytimes.com#after-dfp-ad-bottom
Taranan URL: https://www.nyti

KeyboardInterrupt: 

## Nmap tarama
Nmap (Network Mapper), ağdaki bilgisayarları ve hizmetleri keşfetmek için kullanılan bir güvenlik tarayıcısıdır.

In [107]:
! sudo apt-get install nmap

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  liblinear4 liblua5.3-0 libpcap0.8 lua-lpeg nmap-common
Suggested packages:
  liblinear-tools liblinear-dev ncat ndiff zenmap
The following NEW packages will be installed:
  liblinear4 liblua5.3-0 libpcap0.8 lua-lpeg nmap nmap-common
0 upgraded, 6 newly installed, 0 to remove and 24 not upgraded.
Need to get 6,029 kB of archives.
After this operation, 26.5 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpcap0.8 amd64 1.10.1-4build1 [145 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 liblinear4 amd64 2.3.0+dfsg-5 [41.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 liblua5.3-0 amd64 5.3.6-1build1 [140 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 lua-lpeg amd64 1.0.2-1 [31.4 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/universe

In [108]:
! pip install python-nmap

In [114]:
import nmap

def nmap_scan_by_hostname(hostname):
    nm = nmap.PortScanner()

    # Belirtilen hostname üzerinde TCP taraması yapma
    nm.scan(hostname, arguments='-p 1-65000')

    # Sonuçları ekrana yazdırma
    for host in nm.all_hosts():
        print(f"Host: {host}")
        print("Port\tState\tService")
        for proto in nm[host].all_protocols():
            lport = nm[host][proto].keys()
            for port in sorted(lport):
                state = nm[host][proto][port]['state']
                service = nm[host][proto][port]['name']
                print(f"{port}\t{state}\t{service}")

In [115]:
target_ip = "http://www.nytimes.com"  # Hedef IP adresini değiştirebilirsiniz
nmap_scan_by_hostname(target_ip)